<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-JJK_Project_Server-117fdd22-1aa4-44c2-918d-6e7d63eeab1b</UserSecretsId>
    <RootNamespace>JJK_Project_Server</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LiteNetLib" Version="1.3.5" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
  </ItemGroup>
</Project>